language: python
python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
env:
  - DJANGO_VERSION=2.1.1
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script:
  - pytest
