# Generated by Django 2.1.1 on 2018-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblHappiness',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('user_id', models.CharField()),
                ('team_id', models.CharField()),
                ('date', models.DateTimeField()),
                ('idvl_hpns', models.IntegerField(blank=True, null=True)),
                ('team_hpns', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblReminder',
            fields=[
                ('id', models.CharField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cur_cnt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblTeam',
            fields=[
                ('id', models.CharField(primary_key=True, null=True)),
                ('team_id', models.CharField(serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('wt_start', models.IntegerField(blank=True, null=True)),
                ('wt_end', models.IntegerField(blank=True, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.CharField(primary_key=True, null=True)),
                ('user_id', models.CharField(serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, null=True)),
                ('team_id', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
