# Generated by Django 2.1.1 on 2018-10-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblEvent',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_content', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblHappiness',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=16, null=True)),
                ('team_id', models.CharField(max_length=5, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('idvl_hpns', models.IntegerField(blank=True, null=True)),
                ('team_hpns', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblReminder',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=16, null=True)),
                ('cur_cnt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblTeam',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('wt_start', models.CharField(blank=True, max_length=2, null=True)),
                ('wt_end', models.CharField(blank=True, max_length=2, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('week_push', models.CharField(max_length=7, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=16, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('team_id', models.CharField(max_length=5, null=True)),
                ('first_time', models.CharField(blank=True, max_length=50, null=True)),
                ('first_time_status', models.IntegerField(blank=True, null=True)),
                ('second_time', models.CharField(blank=True, max_length=50, null=True)),
                ('second_time_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
