# Generated by Django 2.1.1 on 2018-10-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_auto_20181011_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
