# Generated by Django 2.1.1 on 2018-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_tbluser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblEvent',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_content', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tblteam',
            options={'ordering': ['name']},
        ),
    ]
